---
extends: default

ignore: |
  .git/
  .venv/
  .venv-codex-usage/

rules:
  braces:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  document-start: disable
  line-length:
    max: 120
    allow-non-breakable-words: true
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  truthy:
    allowed-values: ['true', 'false']
